# Generated by Django 4.2.13 on 2024-05-20 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchChemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=20)),
                ('batch_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_cause', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_returned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.product')),
                ('return_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.reason')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_id', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
                ('time_dispatched', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatch_chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.dispatchchemist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.product')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.trader')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.transporter')),
            ],
        ),
    ]
