# Generated by Django 5.0.6 on 2024-05-27 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchChemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemist_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('SKU', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_cause', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_name', models.CharField(max_length=100)),
                ('trader_address', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=100)),
                ('representative', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_id', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
                ('time_dispatched', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.JSONField(blank=True, default=list)),
                ('dispatch_chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.dispatchchemist')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.trader')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.transporter')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.order')),
                ('product_returned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.product')),
                ('return_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.reason')),
            ],
        ),
    ]
