# Generated by Django 4.2.13 on 2024-05-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="return",
            name="product_returned",
        ),
        migrations.RemoveField(
            model_name="return",
            name="return_reason",
        ),
        migrations.AddField(
            model_name="return",
            name="products",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
