# Generated by Django 4.2.13 on 2024-05-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="return",
            name="destination",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="return",
            name="trader",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="return",
            name="transporter",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
