# Generated by Django 4.2.13 on 2024-05-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.order'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='return_cause',
            field=models.TextField(max_length=200),
        ),
    ]
