# Generated by Django 4.2.13 on 2024-05-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0002_remove_return_product_returned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="return",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dispatcher.order",
                unique=True,
            ),
        ),
    ]
