# Generated by Django 4.2.13 on 2024-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0002_return_destination_return_trader_return_transporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="trader",
            name="username",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
