# Generated by Django 4.2.13 on 2024-05-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_return_order_id_alter_reason_return_cause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
