# Generated by Django 4.2.13 on 2024-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0003_trader_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trader",
            name="username",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
