# Generated by Django 4.2.13 on 2024-05-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0004_alter_trader_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporter",
            name="username",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
