# Generated by Django 4.2.13 on 2024-05-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='batch_number',
            new_name='price',
        ),
    ]
