# Generated by Django 4.2.13 on 2024-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0006_rename_batch_number_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporter',
            old_name='driver',
            new_name='representative',
        ),
        migrations.AddField(
            model_name='transporter',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
