# Generated by Django 4.2.13 on 2024-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0007_rename_driver_transporter_representative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trader",
            name="contact",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="trader_address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
