# Generated by Django 4.2.13 on 2024-05-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatcher", "0008_trader_contact_trader_trader_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchchemist",
            name="contact",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
