# Generated by Django 5.0.6 on 2024-05-27 09:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0009_dispatchchemist_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=[], size=None),
        ),
    ]
