# Generated by Django 5.0.6 on 2024-05-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0012_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100)),
        ),
    ]
